return {}

-- return {
-- 	"mxsdev/nvim-dap-vscode-js",
-- 	dependencies = {
-- 		"mfussenegger/nvim-dap",
-- 	},
-- 	config = function()
-- 		local dap = require("dap")
--
-- 		require("dap-vscode-js").setup({
-- 			debugger_path = "/Users/nurik/.local/bin/vscode-js-debug",
-- 			adapters = { "pwa-node", "pwa-chrome", "pwa-msedge", "node-terminal", "pwa-extensionHost" },
-- 		})
--
-- 		for _, language in ipairs({ "typescript", "javascript" }) do
-- 			require("dap").configurations[language] = {
-- 				{
-- 					type = "pwa-node",
-- 					request = "attach",
-- 					port = 9222,
-- 					processId = require("dap.utils").pick_process,
-- 					name = "Attach debugger to existing `node --inspect` process",
-- 					sourceMaps = true,
-- 					resolveSourceMapLocations = {
-- 						"${workspaceFolder}/**",
-- 						"!**/node_modules/**",
-- 					},
-- 					cwd = "${workspaceFolder}/src",
-- 					skipFiles = { "${workspaceFolder}/node_modules/**/*.js" },
-- 				},
-- 				{
-- 					type = "pwa-chrome",
-- 					name = "Launch Chrome to debug client",
-- 					request = "launch",
-- 					url = "http://localhost:5173",
-- 					sourceMaps = true,
-- 					protocol = "inspector",
-- 					port = 9222,
-- 					webRoot = "${workspaceFolder}/src",
-- 					skipFiles = { "**/node_modules/**/*", "**/@vite/*", "**/src/client/*", "**/src/*" },
-- 				},
-- 				language == "javascript" and {
-- 					type = "pwa-node",
-- 					request = "launch",
-- 					name = "Launch file in new node process",
-- 					program = "${file}",
-- 					cwd = "${workspaceFolder}",
-- 				} or nil,
-- 			}
-- 		end
-- 	end,
-- }
